# Generated by Django 4.2.5 on 2023-10-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordBase', '0002_translation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='english_word',
            field=models.CharField(default=1, max_length=100, verbose_name='English Word'),
            preserve_default=False,
        ),
    ]
