# Generated by Django 4.2.5 on 2023-10-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordBase', '0003_translation_english_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='english_word',
        ),
    ]
