# Generated by Django 4.2.5 on 2023-10-12 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordBase', '0004_remove_translation_english_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='statys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WordBase.statys'),
            preserve_default=False,
        ),
    ]
