# Generated by Django 4.2.5 on 2023-10-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordBase', '0005_statys_translation_statys'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translation',
            name='statys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WordBase.statys'),
        ),
    ]
